APIConf:
  Host: "0.0.0.0"
  Port: 8080

Node: https://evm-rpc-http-reticulum.galactica.com

RegistryAddress: 0x68272A56A0e9b095E5606fDD8b6c297702C0dfe5

MerkleProofService:
  URL: grpc-merkle-9302.galactica.com:443
  TLS: true
