APIConf:
  Host: "0.0.0.0"
  Port: 8080

Node: https://galactica-cassiopeia.g.alchemy.com/public

RegistryAddress: 0xFe35EF5D1E8488a6b06BD35434613917e7d9760f

MerkleProofService:
  URL: grpc-merkle-843843.galactica.com:443
  TLS: true
