APIConf:
  Host: "0.0.0.0"
  Port: 8080

Node: https://galactica-mainnet.g.alchemy.com/public

RegistryAddress: 0xf98E14C33c573c26Bb14d8ca71e1c8756727Be53

MerkleProofService:
  URL: grpc-merkle-613419.galactica.com:443
  TLS: true
