APIConf:
  Host: "0.0.0.0"
  Port: 8080

Node: https://galactica-mainnet.g.alchemy.com/public

RegistryAddress: 0x5fce9D01Fa2f65fF17C3678c7970b8986e9270e4

MerkleProofService:
  URL: grpc-merkle-613419.galactica.com:443
  TLS: true
